# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:12-browsers
  environment:
    NETLIFY_TOKEN: $monorepo_01_netlify

set_env: &set_env
  name: Setup Environment Variables
  command: |
    if [[ $CIRCLE_PULL_REQUEST ]]
    then
      echo 'Fetching Base Commit from GitHub'
      echo 'export CIRCLE_PR_NUMBER="${CIRCLE_PR_NUMBER:-${CIRCLE_PULL_REQUEST##*/}}"' >> $BASH_ENV
      source $BASH_ENV
      echo "export CIRCLE_PR_BASE_SHA=`curl -s https://api.github.com/repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/pulls/${CIRCLE_PR_NUMBER} | jq -r '.base.sha'`" >> $BASH_ENV
      echo 'export AFFECTED_ARGS="--base ${CIRCLE_PR_BASE_SHA}"' >> $BASH_ENV
    else
      echo 'Fetching Base Commit from Deploy Cache'
      if [[ ! -f dist/last-deploy.txt ]]
      then
        mkdir dist && git rev-parse HEAD~1 > dist/last-deploy.txt
      fi
      echo 'export AFFECTED_ARGS="--base $(cat dist/last-deploy.txt)"' >> $BASH_ENV
    fi
    source $BASH_ENV
    echo $AFFECTED_ARGS

yarn_cache: &yarn_cache
  keys:
    - node-deps-node12-{{ checksum "yarn.lock" }}
    # fallback to using the latest cache if no exact match is found
    - node-deps-node12-

deploy_cache: &deploy_cache
  key: last-deploy-sha

yarn_install: &yarn_install
  name: Install Dependencies
  command: yarn install --frozen-lockfile --non-interactive

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          <<: *yarn_cache
      - run:
          <<: *yarn_install
      - save_cache:
          key: node-deps-node12-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache
            - node_modules
  build-LIBS:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          <<: *yarn_cache
      - run: yarn build-libs
      - save_cache:
          key: build_LIBS-{{ .Environment.CIRCLE_WORKFLOW_ID }}
          paths:
            - dist
      - store_artifacts:
          path: dist
      - persist_to_workspace:
          root: .
          paths:
            - dist
  build-IU:
    <<: *defaults
    name: Build IU
    steps:
      - checkout
      - restore_cache:
          <<: *deploy_cache
      - run:
          <<: *set_env
      - restore_cache:
          <<: *yarn_cache
      - attach_workspace:
          at: .
      - run: yarn build:IU
      - save_cache:
          key: build_IU-{{ .Environment.CIRCLE_WORKFLOW_ID }}
          paths:
            - dist
      - store_artifacts:
          path: dist
  deploy-IU:
    <<: *defaults
    name: Deploy IU
    steps:
      - checkout
      - restore_cache:
          <<: *deploy_cache
      - run:
          <<: *set_env
      - restore_cache:
          <<: *yarn_cache
      - restore_cache:
          key: build_IU-{{ .Environment.CIRCLE_WORKFLOW_ID }}
      - run: yarn deploy-sites
      - run: git rev-parse HEAD > dist/last-deploy.txt
      - save_cache:
          key: last-deploy-sha
          paths:
            - dist/last-deploy.txt
  build-MICH:
    <<: *defaults
    name: Build MICH
    steps:
      - checkout
      - restore_cache:
          <<: *deploy_cache
      - run:
          <<: *set_env
      - restore_cache:
          <<: *yarn_cache
      - attach_workspace:
          at: .
      - run: yarn build:MICH
      - save_cache:
          key: build_MICH-{{ .Environment.CIRCLE_WORKFLOW_ID }}
          paths:
            - dist
      - store_artifacts:
          path: dist
  deploy-MICH:
    <<: *defaults
    name: Deploy MICH
    steps:
      - checkout
      - restore_cache:
          <<: *deploy_cache
      - run:
          <<: *set_env
      - restore_cache:
          <<: *yarn_cache
      - restore_cache:
          key: build_MICH-{{ .Environment.CIRCLE_WORKFLOW_ID }}
      - run: yarn deploy-sites
      - run: git rev-parse HEAD > dist/last-deploy.txt
      - save_cache:
          key: last-deploy-sha
          paths:
            - dist/last-deploy.txt
workflows:
  version: 2
  pr_check:
    jobs:
      - install
      - build-LIBS:
          requires:
            - install
      - build-IU:
          requires:
            - install
            - build-LIBS
      - build-MICH:
          requires:
            - install
            - build-LIBS
      - deploy-IU:
          requires:
            - build-LIBS
            - build-IU
      - deploy-MICH:
          requires:
            - build-LIBS
            - build-MICH
#          filters:
#            branches:
#              only:
#                - master

